import { expect, it } from "vitest"
import { PracticeSession } from "../practice"

it("allows wrong characters, smart backspace, correct-word locks and word deletion", () => {
	const session = new PracticeSession("one two three")
	expect(session.processKey("ArrowLeft", 0).typo).toBe(false)
	session.processKey("x", 100)
	expect(session.getSnapshot().cursor).toBe(1)
	expect(session.getSnapshot().metrics.accuracy).toBe(0)
	session.processKey("Backspace", 200)
	for (const key of "one tw") session.processKey(key, 300)
	session.processKey("DeleteWord", 350)
	expect(session.getSnapshot().currentInput).toBe("one ")
	session.processKey("Backspace", 360)
	expect(session.getSnapshot().currentInput).toBe("one ")
	for (const key of "two three") session.processKey(key, 1000)
	expect(session.getSnapshot().complete).toBe(true)
	expect(session.getSnapshot().metrics.accuracy).toBe(100)
	expect(session.processKey("x", 1100).typo).toBe(false)
	expect(session.getSnapshot().metrics.maxCombo).toBe(13)
})

it("pads skipped text without scoring it as correct and lets modern input repair it", () => {
	const session = new PracticeSession("hello world")
	for (const key of "h ") session.processKey(key, 300)
	expect(session.getSnapshot().currentInput).toBe("h     ")
	session.processKey("Backspace", 400)
	expect(session.getSnapshot().currentInput).toBe("h")
	for (const key of "ello world") session.processKey(key, 1000)
	expect(session.getSnapshot().complete).toBe(true)
	const last = new PracticeSession("hello")
	last.processKey("h", 0)
	last.processKey(" ", 0)
	expect(last.getSnapshot().complete).toBe(true)
	expect(last.getSnapshot().metrics.accuracy).toBe(20)
})

it("classic confirms the last word with space, locks prior words and ignores empty spaces", () => {
	const session = new PracticeSession("one two", "classic")
	expect(session.getSnapshot().metrics.accuracy).toBe(100)
	session.processKey(" ", 0)
	expect(session.getSnapshot().cursor).toBe(0)
	for (const key of "x ") session.processKey(key, 200)
	session.processKey("Backspace", 300)
	expect(session.getSnapshot().currentInput).toBe("x   ")
	for (const key of "two") session.processKey(key, 1000)
	expect(session.getSnapshot().complete).toBe(false)
	session.processKey(" ", 1100)
	expect(session.getSnapshot().complete).toBe(true)
	expect(session.getSnapshot().metrics.incorrectKeystrokes).toBe(2)
	const overflow = new PracticeSession("one", "classic")
	for (const key of "oneX ") overflow.processKey(key, 1200)
	expect(overflow.getSnapshot().metrics.accuracy).toBeLessThan(100)
	const multiple = new PracticeSession("one two three", "classic")
	for (const key of "oneXXw") multiple.processKey(key, 1200)
	expect(multiple.getSnapshot().cursor).toBe(3)
	expect(multiple.getSnapshot().metrics.correctKeystrokes).toBe(3)
	multiple.processKey(" ", 1300)
	expect(multiple.getSnapshot().currentInput).toBe("one ")
	expect(multiple.getSnapshot().cursor).toBe(4)
	expect(multiple.getSnapshot().complete).toBe(false)
	for (const key of "two three ") multiple.processKey(key, 1400)
	expect(multiple.getSnapshot().complete).toBe(true)
})

it("extends timed text without resetting input, mistakes or elapsed time", () => {
	const session = new PracticeSession("one")
	for (const key of "one") session.processKey(key, 1000)
	session.appendText("two")
	expect(session.getSnapshot().complete).toBe(false)
	expect(session.getSnapshot().cursor).toBe(3)
	for (const key of " two") session.processKey(key, 2000)
	expect(session.getSnapshot(3000).targetText).toBe("one two")
	expect(session.getSnapshot().metrics.elapsedMs).toBe(3000)
	const empty = new PracticeSession("")
	empty.processKey("DeleteWord", 0)
	empty.processKey("Backspace", 0)
	expect(empty.getSnapshot().cursor).toBe(0)
	expect(empty.processKey("x", 0).typo).toBe(true)
})
